"""Type stubs for fuzzgpu public API."""
from __future__ import annotations
from typing import Callable, Iterable, Optional, Sequence, Tuple

import numpy as np
from numpy.typing import NDArray

Processor = Optional[Callable[[str], str]]
Scorer = Callable[..., float]

# ── Version ──────────────────────────────────────────────────
__version__: str

# ── Levenshtein ──────────────────────────────────────────────
def levenshtein_distance(a: str, b: str) -> int: ...
def levenshtein(a: str, b: str) -> int: ...
def levenshtein_batch(query: str, candidates: Sequence[str]) -> list[int]: ...
def levenshtein_batch_into(query: str, candidates: Sequence[str], out: NDArray[np.uint32]) -> None: ...
def levenshtein_cdist(list_a: Sequence[str], list_b: Sequence[str]) -> list[list[int]]: ...
def levenshtein_cdist_into(list_a: Sequence[str], list_b: Sequence[str], out: NDArray[np.uint32]) -> None: ...
def levenshtein_myers(a: str, b: str) -> int: ...

# ── Damerau-Levenshtein (unrestricted Lowrance-Wagner) ───────
def damerau_levenshtein_distance(a: str, b: str) -> int: ...
def damerau_levenshtein(a: str, b: str) -> int: ...
def damerau(a: str, b: str) -> int: ...
def damerau_levenshtein_batch(query: str, candidates: Sequence[str]) -> list[int]: ...
def damerau_levenshtein_batch_into(query: str, candidates: Sequence[str], out: NDArray[np.uint32]) -> None: ...
def damerau_levenshtein_cdist(list_a: Sequence[str], list_b: Sequence[str]) -> list[list[int]]: ...
def damerau_levenshtein_cdist_into(list_a: Sequence[str], list_b: Sequence[str], out: NDArray[np.uint32]) -> None: ...
def damerau_ratio(a: str, b: str) -> float: ...

# ── Needleman-Wunsch ─────────────────────────────────────────
def needleman_wunsch_score(a: str, b: str, match_score: int, mismatch_score: int, gap_penalty: int) -> int: ...
def needleman_wunsch(a: str, b: str, match_score: int, mismatch_score: int, gap_penalty: int) -> int: ...
def needleman_wunsch_batch(query: str, candidates: Sequence[str], match_score: int, mismatch_score: int, gap_penalty: int) -> list[int]: ...
def needleman_wunsch_affine(a: str, b: str, match_score: int, mismatch_score: int, gap_open: int, gap_extend: int) -> int: ...
def needleman_wunsch_affine_batch(query: str, candidates: Sequence[str], match_score: int, mismatch_score: int, gap_open: int, gap_extend: int) -> list[int]: ...
def needleman_wunsch_striped(a: str, b: str, match_score: int, mismatch_score: int, gap_penalty: int) -> int: ...

# ── Jaro / Jaro-Winkler ──────────────────────────────────────
def jaro_similarity(a: str, b: str) -> float: ...
def jaro(a: str, b: str) -> float: ...
def jaro_winkler_similarity(a: str, b: str, p: float = 0.1) -> float: ...
def jaro_winkler(a: str, b: str, p: float = 0.1) -> float: ...
def jaro_optimized(a: str, b: str) -> float: ...
def jaro_winkler_batch(query: str, candidates: Sequence[str], p: float = 0.1) -> list[float]: ...
def jaro_winkler_batch_into(query: str, candidates: Sequence[str], out: NDArray[np.float64], p: float = 0.1) -> None: ...
def jaro_winkler_cdist(list_a: Sequence[str], list_b: Sequence[str], p: float = 0.1) -> list[list[float]]: ...
def jaro_winkler_cdist_into(list_a: Sequence[str], list_b: Sequence[str], out: NDArray[np.float64], p: float = 0.1) -> None: ...

# ── Fuzzy ratios ─────────────────────────────────────────────
def ratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def partial_ratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def partial_ratio_alignment(
    s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0
) -> ScoreAlignment: ...
def token_sort_ratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def token_set_ratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def token_ratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def partial_token_sort_ratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def partial_token_set_ratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def partial_token_ratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def QRatio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def WRatio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def wratio(s1: str, s2: str, *, processor: Processor = None, score_cutoff: float = 0.0) -> float: ...
def ratio_batch(query: str, candidates: Sequence[str], *, processor: Processor = None, score_cutoff: float = 0.0, workers: Optional[int] = None) -> list[float]: ...

# ── Search ───────────────────────────────────────────────────
def extract(
    query: str,
    choices: Iterable[str],
    score_cutoff: float = 0.0,
    limit: int = 5,
    *,
    scorer: Scorer = ...,
    processor: Processor = None,
    score_hint: Optional[float] = None,
    scorer_kwargs: Optional[dict] = None,
) -> list[Tuple[str, float, int]]: ...

def extractOne(
    query: str,
    choices: Iterable[str],
    score_cutoff: float = 0.0,
    *,
    scorer: Scorer = ...,
    processor: Processor = None,
    score_hint: Optional[float] = None,
    scorer_kwargs: Optional[dict] = None,
) -> Optional[Tuple[str, float, int]]: ...

def extract_one(
    query: str,
    choices: Iterable[str],
    score_cutoff: float = 0.0,
    *,
    scorer: Scorer = ...,
    processor: Processor = None,
    score_hint: Optional[float] = None,
    scorer_kwargs: Optional[dict] = None,
) -> Optional[Tuple[str, float, int]]: ...

# ── Utilities ────────────────────────────────────────────────
def set_cpu_only(cpu_only: bool) -> None: ...
def set_gpu_threshold(threshold: Optional[int]) -> None: ...
def is_gpu_available() -> bool: ...
def warmup() -> tuple[bool, str]: ...
def gpu_info() -> str: ...
def hardware_info() -> str: ...

# ── Alignment helpers (rapidfuzz.distance API) ───────────────
class Editop(Tuple[str, int, int]):
    tag: str
    src_pos: int
    dest_pos: int

class Editops(list):
    _editops: list[Editop]
    _src_len: int
    _dest_len: int

    def src_len(self) -> int: ...
    def dest_len(self) -> int: ...
    def as_list(self) -> list[Tuple[str, int, int]]: ...
    def as_opcodes(self) -> "Opcodes": ...
    def as_matching_blocks(self) -> list["MatchingBlock"]: ...
    def inverse(self) -> "Editops": ...
    def apply(self, src: Sequence, dest: Sequence) -> tuple: ...
    def copy(self) -> "Editops": ...
    def remove_subsequence(self, other: Sequence) -> "Editops": ...
    @staticmethod
    def from_opcodes(opcodes: list) -> "Editops": ...

class Opcode(Tuple[str, int, int, int, int]):
    tag: str
    src_start: int
    src_end: int
    dest_start: int
    dest_end: int

class Opcodes(list):
    _opcodes: list[Opcode]
    _src_len: int
    _dest_len: int

    def src_len(self) -> int: ...
    def dest_len(self) -> int: ...
    def as_list(self) -> list[Tuple[str, int, int, int, int]]: ...
    def as_editops(self) -> Editops: ...
    def as_matching_blocks(self) -> list["MatchingBlock"]: ...
    def apply(self, src: Sequence, dest: Sequence) -> tuple: ...
    def copy(self) -> "Opcodes": ...
    def inverse(self) -> "Opcodes": ...
    @staticmethod
    def from_editops(editops: list) -> "Opcodes": ...

class MatchingBlock(Tuple[int, int, int]):
    src_start: int
    dest_start: int
    size: int

class ScoreAlignment(Tuple[float, int, int, int, int]):
    score: float
    src_start: int
    src_end: int
    dest_start: int
    dest_end: int
