from typing import Callable, Iterable, TypeAlias

Scorer: TypeAlias = Callable[..., float]
def ratio(s1: str, s2: str, *, processor: Callable[[str], str] | None = ..., score_cutoff: float = ...) -> float: ...
def partial_ratio(s1: str, s2: str, *, processor: Callable[[str], str] | None = ..., score_cutoff: float = ...) -> float: ...
def extract(query: str, choices: Iterable[str], *, scorer: Scorer = ..., processor: Callable[[str], str] | None = ..., limit: int | None = ..., score_cutoff: float = ...) -> list[tuple[str, float, int]]: ...
def extractOne(query: str, choices: Iterable[str], *, scorer: Scorer = ..., processor: Callable[[str], str] | None = ..., score_cutoff: float = ...) -> tuple[str, float, int] | None: ...
