from typing import Callable, Iterable
Processor = Callable[[str], str]
def ratio(a: str, b: str, *, processor: Processor | None = ..., score_cutoff: float = ...) -> float: ...
def partial_ratio(a: str, b: str, *, processor: Processor | None = ..., score_cutoff: float = ...) -> float: ...
def token_sort_ratio(a: str, b: str, *, processor: Processor | None = ..., score_cutoff: float = ...) -> float: ...
def token_set_ratio(a: str, b: str, *, processor: Processor | None = ..., score_cutoff: float = ...) -> float: ...
def partial_token_sort_ratio(a: str, b: str, *, processor: Processor | None = ..., score_cutoff: float = ...) -> float: ...
def partial_token_set_ratio(a: str, b: str, *, processor: Processor | None = ..., score_cutoff: float = ...) -> float: ...
def QRatio(a: str, b: str, *, processor: Processor | None = ..., score_cutoff: float = ...) -> float: ...
def WRatio(a: str, b: str, *, processor: Processor | None = ..., score_cutoff: float = ...) -> float: ...
def ratio_batch(query: str, candidates: Iterable[str], *, processor: Processor | None = ..., score_cutoff: float = ..., workers: int | None = ...) -> list[float]: ...
