from typing import Callable, Iterable, Optional, Sequence
Processor = Callable[[str], str]

def ratio(a: str, b: str, *, processor: Optional[Processor] = ..., score_cutoff: float = ...) -> float: ...
def partial_ratio(a: str, b: str, *, processor: Optional[Processor] = ..., score_cutoff: float = ...) -> float: ...
def token_sort_ratio(a: str, b: str, *, processor: Optional[Processor] = ..., score_cutoff: float = ...) -> float: ...
def token_set_ratio(a: str, b: str, *, processor: Optional[Processor] = ..., score_cutoff: float = ...) -> float: ...
def partial_token_sort_ratio(a: str, b: str, *, processor: Optional[Processor] = ..., score_cutoff: float = ...) -> float: ...
def partial_token_set_ratio(a: str, b: str, *, processor: Optional[Processor] = ..., score_cutoff: float = ...) -> float: ...
def QRatio(a: str, b: str, *, processor: Optional[Processor] = ..., score_cutoff: float = ...) -> float: ...
def WRatio(a: str, b: str, *, processor: Optional[Processor] = ..., score_cutoff: float = ...) -> float: ...
wratio = WRatio
def ratio_batch(query: str, candidates: Sequence[str], *, processor: Optional[Processor] = ..., score_cutoff: float = ..., workers: Optional[int] = ...) -> list[float]: ...
def extract(
    query: str,
    choices: Iterable[str],
    score_cutoff: float = ...,
    limit: int = ...,
    *,
    scorer: Callable = ...,
    processor: Optional[Processor] = ...,
    score_hint: Optional[float] = ...,
    scorer_kwargs: Optional[dict] = ...,
) -> list[tuple[str, float, int]]: ...
def extractOne(
    query: str,
    choices: Iterable[str],
    score_cutoff: float = ...,
    *,
    scorer: Callable = ...,
    processor: Optional[Processor] = ...,
    score_hint: Optional[float] = ...,
    scorer_kwargs: Optional[dict] = ...,
) -> Optional[tuple[str, float, int]]: ...
extract_one = extractOne
damerau_ratio: Callable[[str, str], float]
