from typing import Callable, Iterable, Iterator
Scorer = Callable[..., float]
def extract_iter(query: str, choices: Iterable[str], *, scorer: Scorer = ..., processor: Callable[[str], str] | None = ..., score_cutoff: float = ...) -> Iterator[tuple[str, float, int]]: ...
def extract(query: str, choices: Iterable[str], score_cutoff: float = ..., limit: int | None = ..., *, scorer: Scorer = ..., processor: Callable[[str], str] | None = ...) -> list[tuple[str, float, int]]: ...
def extractOne(query: str, choices: Iterable[str], score_cutoff: float = ..., *, scorer: Scorer = ..., processor: Callable[[str], str] | None = ...) -> tuple[str, float, int] | None: ...
def cdist(queries: Iterable[str], choices: Iterable[str], *, scorer: Scorer = ..., processor: Callable[[str], str] | None = ...) -> list[list[float]]: ...
